// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvluZunMfss4PUV06JYUqxveVNkiPAfb4',
    appId: '1:413426387482:web:ea50be6f457ab054295fa3',
    messagingSenderId: '413426387482',
    projectId: 'rentals-f9de4',
    authDomain: 'rentals-f9de4.firebaseapp.com',
    storageBucket: 'rentals-f9de4.firebasestorage.app',
    measurementId: 'G-RJN63WR62H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9qpfZXPuNP_sprIL71uZoqIZlREsZxo',
    appId: '1:413426387482:ios:60907a6173f0f51b295fa3',
    messagingSenderId: '413426387482',
    projectId: 'rentals-f9de4',
    storageBucket: 'rentals-f9de4.firebasestorage.app',
    iosBundleId: 'com.example.rentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9qpfZXPuNP_sprIL71uZoqIZlREsZxo',
    appId: '1:413426387482:ios:60907a6173f0f51b295fa3',
    messagingSenderId: '413426387482',
    projectId: 'rentals-f9de4',
    storageBucket: 'rentals-f9de4.firebasestorage.app',
    iosBundleId: 'com.example.rentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvluZunMfss4PUV06JYUqxveVNkiPAfb4',
    appId: '1:413426387482:web:6c15f7817bfd6689295fa3',
    messagingSenderId: '413426387482',
    projectId: 'rentals-f9de4',
    authDomain: 'rentals-f9de4.firebaseapp.com',
    storageBucket: 'rentals-f9de4.firebasestorage.app',
    measurementId: 'G-FYBE5PJ2ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUvkEgiR5fqh2I-o6YAqLf0CnwdXCyns',
    appId: '1:413426387482:android:6d8e2202d941ac5e295fa3',
    messagingSenderId: '413426387482',
    projectId: 'rentals-f9de4',
    storageBucket: 'rentals-f9de4.firebasestorage.app',
  );

}